// Generated by CoffeeScript 1.6.2
var Service, svc;

Service = require("node-linux").Service;

svc = new Service({
  name: "virtualmin-backup-dropbox",
  description: "Backup virtualmin server backup files to dropbox.",
  script: require("path").join(__dirname, "index.js"),
  env: {
    name: "NODE_ENV",
    value: "production"
  }
});

svc.on("install", function() {
  return console.log("\nInstallation Complete\n---------------------");
});

svc.on("alreadyinstalled", function() {
  console.log("This service is already installed.");
  console.log("Attempting to start it.");
  return svc.start();
});

svc.on("start", function() {
  return console.log(svc.name + " started!\nVisit http://127.0.0.1:3000 to see it in action.\n");
});

svc.install();
