// Generated by CoffeeScript 1.6.2
var Service, svc;

Service = require("node-linux").Service;

svc = new Service({
  name: "virtualmin-backup-dropbox",
  script: require("path").join(__dirname, "index.js")
});

svc.on("uninstall", function() {
  console.log("Uninstall complete.");
  return console.log("The service exists: ", svc.exists);
});

svc.on("error", function(err) {
  return console.log("ERROR:", err);
});

svc.uninstall();
