// Generated by CoffeeScript 1.6.2
var showError;

module.exports = showError = function(error) {
  switch (error.status) {
    case Dropbox.ApiError.INVALID_TOKEN:
    case Dropbox.ApiError.NOT_FOUND:
    case Dropbox.ApiError.OVER_QUOTA:
    case Dropbox.ApiError.RATE_LIMITED:
    case Dropbox.ApiError.NETWORK_ERROR:
    case Dropbox.ApiError.INVALID_PARAM:
    case Dropbox.ApiError.OAUTH_ERROR:
    case Dropbox.ApiError.INVALID_METHOD:
      break;
    default:
      throw error;
  }
};
